@STANWEBAPI_HostAddress = http://localhost:5161

POST {{STANWEBAPI_HostAddress}}/api/v1/auth/sign-up
Accept: application/json
Content-Type: application/json

{
    "name": "",
    "surname": "string",
    "email": "string",
    "password": "string",
    "south_african_identity_number": "string",
    "phone_number": "string"
}

###
